### ISSUE TITLE
build automation chapter

### ISSUE THREAD

**Issue by magnusmunch** [rr-mrc-bsu/reproducible-research#12]
this chapter is on build automation of projects
- [ ] makefile pipeline
- [ ] snakemake pipeline

**Comment by magnusmunch** [comment]
Yes an example would be nice. I was thinking as an example a large project that involves a (or multiple) .Rmd reports, that depend on some .R data analysis scripts and simulation scripts, that in turn depend on an R package build or something.

**Comment by kkmann** [comment]
Sure, I just feel that a learning example should not overcomplicate things. Complex enough to see the benefit but otherwise as simple as possible - I'd say a dummy analysis on iris is just fine, but maybe I am just too lazy ;)

**Comment by evigorito** [comment]
sorry, I havent used make myself


best wishes


elens

________________________________

**Comment by kkmann** [comment]
@magnusmunch why don't u open a PR already, makes it easier to work/directly comment on changes.

**Comment by kkmann** [comment]
#13

**Comment by kkmann** [comment]
Well, maybe we should keep this issue open since there are still quite a few [todos] ;) We will also need to get an example repository going at some point.

**Comment by kkmann** [comment]
How are we going to organize the examples? Do we want to check the examples using TravisCI?

**Comment by magnusmunch** [comment]
I guess it might be useful to have an example for a few other chapters as well. Would probably be good to combine them in one example repo. Can we have travis build whatever we want it to (.Rmd files etc), or is it limited to packages and such?

**Comment by kkmann** [comment]
travis can do a lot - although it sometimes needs a bit of hacking since the R build environment is geared towards packages. Take a look at the travis configuration for this repo: we are not only using it to build the book but also to deploy it (the book content gets pushed to the gh-pages branch which is what you see when following the link to the github pages page of this repo).

**Comment by kkmann** [comment]
>  Would probably be good to combine them in one example repo

I'd suggest we should have different minimal-working example repositories to make things more accessible / focus on the relevant parts.

**Comment by kkmann** [comment]
@magnusmunch to get things rolling, I initialized an example repository with a fairly simple Makefile - feel free to modify anything you like! Do you think you could get the demo repo in sync with the 'make' section of the chapter?

**Comment by magnusmunch** [comment]
I have a simple example in the pull request I just made, but it will probably change. I think I should be able to sync the demo repo and chapter at some point.

**Comment by magnusmunch** [comment]
By the way, I'm storing R generated figures in the Figures folder, but am not sure whether to include the folder in the .gitignore file or not. There is already the funny mouse there that shouldn't be ignored I guess.

**Comment by kkmann** [comment]
Hm, I'd prefer to keep examples and book in separate repositories. My main argument would be, that it should be possible to quickly clone the example repos without getting the whole complexity behind our book ;) But I am open to discussing that if you have a convincing argument for including the example code in the boo repository! Also, if you already went through the trouble of writing an example of your own - feel free to replace any content in the example repo, it was just a (boring) suggestion!

**Comment by kkmann** [comment]
> By the way, I'm storing R generated figures in the Figures folder, but am not sure whether to include the folder in the .gitignore file or not. There is already the funny mouse there that shouldn't be ignored I guess.

Well, you don't need to store them at all - markdown should take care of that. We only need the Figures folder for static images (like the marvelous hamster!)

**Comment by kkmann** [comment]
Don't wait too long before opening a PR, if there is an issue we can fix it easier once the PR is open. If you are doing complicated stuff, do it in small steps so that we can follow along ;) It is perfectly fine to indicate that a PR is not ready to merge.

**Comment by magnusmunch** [comment]
Just for keeping branches and chapters kind of in sync, I split the ci-and-build-automation branch into a continuous-integration and build-automation branch.

**Comment by kkmann** [comment]
@magnusmunch - if I see it correctly now we still need to make sure that the build-automation (or maybe better workflow automation?) chapter is in sync with the example repository. 

I really don't care about the example at all - so feel free to upload your code if you want! It was just a suggestion to get things started. Otherwise, we'd need to modify the makefile section.

Are you also interested in exploring snakemake or would you prefer to have somebody else work on that? In that case are you happy to keep the snakemake/make example in the same repository? I think the two techniques are so closely related that it would be better to have a direct comparison and be able to play around with both in the same repository.

**Comment by magnusmunch** [comment]
Yes, I'm working on syncing the example repo and chapter example. If you think they are strongly related I would keep them in the same repository, I don't mind. 

I'm not a python user, so I'm not sure how long it would take me to write something on it. At first glance it does look very similar to make, but might be better if someone at least helped with it.

**Comment by kkmann** [comment]
I am happy to cover snakemake - focus on getting a neat 'make' part and I will try to work along your lines and highlight the differences / additional benefits of using snakemake.

to get things organized a bit, I set up a milestone for this chapter and split this issue in two: #24 #25 

Closing this one.
